version: '3.8'

services:
  #dmit_email_sender_db:
  #  image: postgres:14
  #  restart: always
  #  ports:
  #    - 5433:5432
  #  environment:
  #    - POSTGRES_DB=email_sender
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=311034
  #  container_name: dmit_email_sender_db
  #  volumes:
  #    - ./postgres-data-email-sender:/var/lib/postgresql/data
  #  networks:
  #    - dmit_network

  dmit_email_sender_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dmit_email_sender_app
    ports:
      - "3001:3000"
    networks:
      - dmit_network

networks:
  dmit_network:
    external: true
